sudo: required
services:
  - docker

before_install:
  - docker build -t dwp32/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dwp32/docker-react npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-??????"
#  bucket_path: "Docker-env"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_acces_key:
#    secure: "$AWS_SECRET_KEY"